// Generated by purs bundle 0.12.0
var PS = {};
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Functor"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Function = PS["Data.Function"];
  var Data_Unit = PS["Data.Unit"];                 
  var Functor = function (map) {
      this.map = map;
  };
  var map = function (dict) {
      return dict.map;
  };
  exports["Functor"] = Functor;
  exports["map"] = map;
})(PS["Data.Functor"] = PS["Data.Functor"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Control.Apply"];
  var Control_Category = PS["Control.Category"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];                 
  var Apply = function (Functor0, apply) {
      this.Functor0 = Functor0;
      this.apply = apply;
  };                      
  var apply = function (dict) {
      return dict.apply;
  };
  exports["Apply"] = Apply;
  exports["apply"] = apply;
})(PS["Control.Apply"] = PS["Control.Apply"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Apply = PS["Control.Apply"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Unit = PS["Data.Unit"];                 
  var Applicative = function (Apply0, pure) {
      this.Apply0 = Apply0;
      this.pure = pure;
  };
  var pure = function (dict) {
      return dict.pure;
  };
  var liftA1 = function (dictApplicative) {
      return function (f) {
          return function (a) {
              return Control_Apply.apply(dictApplicative.Apply0())(pure(dictApplicative)(f))(a);
          };
      };
  };
  exports["Applicative"] = Applicative;
  exports["pure"] = pure;
  exports["liftA1"] = liftA1;
})(PS["Control.Applicative"] = PS["Control.Applicative"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Control.Bind"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Category = PS["Control.Category"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Unit = PS["Data.Unit"];                 
  var Bind = function (Apply0, bind) {
      this.Apply0 = Apply0;
      this.bind = bind;
  };                     
  var bind = function (dict) {
      return dict.bind;
  };
  exports["Bind"] = Bind;
  exports["bind"] = bind;
})(PS["Control.Bind"] = PS["Control.Bind"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Unit = PS["Data.Unit"];                 
  var Monad = function (Applicative0, Bind1) {
      this.Applicative0 = Applicative0;
      this.Bind1 = Bind1;
  };
  var ap = function (dictMonad) {
      return function (f) {
          return function (a) {
              return Control_Bind.bind(dictMonad.Bind1())(f)(function (v) {
                  return Control_Bind.bind(dictMonad.Bind1())(a)(function (v1) {
                      return Control_Applicative.pure(dictMonad.Applicative0())(v(v1));
                  });
              });
          };
      };
  };
  exports["Monad"] = Monad;
  exports["ap"] = ap;
})(PS["Control.Monad"] = PS["Control.Monad"] || {});
(function(exports) {
    "use strict";

  exports.pureE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };
})(PS["Effect"] = PS["Effect"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Effect"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Monad = PS["Control.Monad"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Prelude = PS["Prelude"];                 
  var monadEffect = new Control_Monad.Monad(function () {
      return applicativeEffect;
  }, function () {
      return bindEffect;
  });
  var bindEffect = new Control_Bind.Bind(function () {
      return applyEffect;
  }, $foreign.bindE);
  var applyEffect = new Control_Apply.Apply(function () {
      return functorEffect;
  }, Control_Monad.ap(monadEffect));
  var applicativeEffect = new Control_Applicative.Applicative(function () {
      return applyEffect;
  }, $foreign.pureE);
  var functorEffect = new Data_Functor.Functor(Control_Applicative.liftA1(applicativeEffect));
  exports["functorEffect"] = functorEffect;
  exports["applyEffect"] = applyEffect;
  exports["applicativeEffect"] = applicativeEffect;
  exports["bindEffect"] = bindEffect;
  exports["monadEffect"] = monadEffect;
})(PS["Effect"] = PS["Effect"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Category = PS["Control.Category"];
  var Control_Monad = PS["Control.Monad"];
  var Effect = PS["Effect"];                                 
  var liftEffect = function (dict) {
      return dict.liftEffect;
  };
  exports["liftEffect"] = liftEffect;
})(PS["Effect.Class"] = PS["Effect.Class"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Monad = PS["Control.Monad"];
  var Control_Monad_Cont_Class = PS["Control.Monad.Cont.Class"];
  var Control_Monad_Error_Class = PS["Control.Monad.Error.Class"];
  var Control_Monad_Reader_Class = PS["Control.Monad.Reader.Class"];
  var Control_Monad_Rec_Class = PS["Control.Monad.Rec.Class"];
  var Control_Monad_State_Class = PS["Control.Monad.State.Class"];
  var Control_Monad_Trans_Class = PS["Control.Monad.Trans.Class"];
  var Control_Monad_Writer_Class = PS["Control.Monad.Writer.Class"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_MonadZero = PS["Control.MonadZero"];
  var Control_Plus = PS["Control.Plus"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Distributive = PS["Data.Distributive"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Newtype = PS["Data.Newtype"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Effect_Class = PS["Effect.Class"];
  var Prelude = PS["Prelude"];                 
  var ReaderT = function (x) {
      return x;
  };
  exports["ReaderT"] = ReaderT;
})(PS["Control.Monad.Reader.Trans"] = PS["Control.Monad.Reader.Trans"] || {});
(function(exports) {
  /* global exports */
  "use strict";
  var React =require("react"); 

  function createClass(baseClass) {
    function bindProperty(instance, prop, value) {
      switch (prop) {
        case 'state':
        case 'render':
        case 'componentDidMount':
        case 'componentWillUnmount':
          instance[prop] = value;
          break;

        case 'componentDidCatch':
        case 'componentWillUpdate':
        case 'shouldComponentUpdate':
        case 'getSnapshotBeforeUpdate':
          instance[prop] = function (a, b) { return value(a)(b)(); };
          break;

        case 'componentDidUpdate':
          instance[prop] = function (a, b, c) { return value(a)(b)(c)(); };
          break;

        case 'unsafeComponentWillMount':
          instance['UNSAFE_componentWillMount'] = value;
          break;

        case 'unsafeComponentWillReceiveProps':
          instance['UNSAFE_componentWillReceiveProps'] = function (a) { return value(a)(); };
          break;

        case 'unsafeComponentWillUpdate':
          instance['UNSAFE_componentWillUpdate'] = function (a, b) { return value(a)(b)(); };
          break;

        default:
          throw new Error('[purescript-react] Not a component property: ' + prop);
      }
    }

    return function (displayName) {
      return function (ctrFn) {
        var Constructor = function (props) {
          baseClass.call(this, props);
          var spec = ctrFn(this)();
          for (var k in spec) {
            bindProperty(this, k, spec[k]);
          }
        };

        Constructor.displayName = displayName;
        Constructor.prototype = Object.create(baseClass.prototype);
        Constructor.prototype.constructor = Constructor;

        return Constructor;
      };
    };
  }

  function createClassWithDerivedState(classCtr) {
    return function(displayName) {
      return function(getDerivedStateFromProps) {
        return function(ctrFn) {
          var Constructor = componentImpl(displayName)(ctrFn);
          Constructor.getDerivedStateFromProps = function(a, b) { return getDerivedStateFromProps(a)(b) };
          return Constructor;
        };
      };
    };
  }

  var componentImpl = createClass(React.Component);
  exports.componentImpl = componentImpl;                                                     

  exports.statelessComponent = function(x) { return x; };

  function getProps(this_) {
    return function(){
      return this_.props;
    };
  }
  exports.getProps = getProps;                 

  function setStateImpl(this_) {
    return function(state){
      return function(){
        this_.setState(state);
      };
    };
  }                                   

  function setStateWithCallbackImpl(this_) {
    return function(state){
      return function(cb){
        return function() {
          this_.setState(state, cb);
        };
      };
    };
  }                                                           

  function getState(this_) {
    return function(){
      if (!this_.state) {
        throw new Error('[purescript-react] Cannot get state within constructor');
      }
      return this_.state;
    };
  }
  exports.getState = getState;

  function forceUpdateWithCallback(this_) {
    return function(cb) {
      return function() {
        this_.forceUpdate(cb);
      };
    };
  }                                                         

  function createElement(class_) {
    return function(props){
      return function(children){
        return React.createElement.apply(React, [class_, props].concat(children));
      };
    };
  }
  exports.createElementImpl = createElement;   

  function createLeafElement(class_) {
    return function(props) {
      return React.createElement(class_, props);
    };
  }
  exports.createLeafElementImpl = createLeafElement;

  function createElementDynamic(class_) {
    return function(props) {
      return function(children){
        return React.createElement(class_, props, children);
      };
    };
  };                                                         

  function createContext(defaultValue) {
    var context = React.createContext(defaultValue);
    return {
      consumer: context.Consumer,
      provider: context.Provider
    };
  }
})(PS["React"] = PS["React"] || {});
(function(exports) {
    "use strict";

  // module Unsafe.Coerce

  exports.unsafeCoerce = function (x) {
    return x;
  };
})(PS["Unsafe.Coerce"] = PS["Unsafe.Coerce"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Unsafe.Coerce"];
  exports["unsafeCoerce"] = $foreign.unsafeCoerce;
})(PS["Unsafe.Coerce"] = PS["Unsafe.Coerce"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["React"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Category = PS["Control.Category"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Nullable = PS["Data.Nullable"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Unit = PS["Data.Unit"];
  var Effect = PS["Effect"];
  var Effect_Exception = PS["Effect.Exception"];
  var Effect_Uncurried = PS["Effect.Uncurried"];
  var Prelude = PS["Prelude"];
  var Type_Row = PS["Type.Row"];
  var Unsafe_Coerce = PS["Unsafe.Coerce"];                 
  var ReactComponentSpec = {};    
  var ReactPropFields = {};              
  var unsafeCreateLeafElement = $foreign.createLeafElementImpl;      
  var unsafeCreateElement = $foreign.createElementImpl;
  var reactPropFields = function (dictUnion) {
      return function (dictUnion1) {
          return ReactPropFields;
      };
  };
  var reactComponentSpec = function (dictUnion) {
      return function (dictNub) {
          return ReactComponentSpec;
      };
  };
  var createLeafElement = function (dictReactPropFields) {
      return $foreign.createLeafElementImpl;
  };
  var component = function (dictReactComponentSpec) {
      return $foreign.componentImpl;
  };
  exports["ReactComponentSpec"] = ReactComponentSpec;
  exports["component"] = component;
  exports["ReactPropFields"] = ReactPropFields;
  exports["unsafeCreateElement"] = unsafeCreateElement;
  exports["createLeafElement"] = createLeafElement;
  exports["unsafeCreateLeafElement"] = unsafeCreateLeafElement;
  exports["reactComponentSpec"] = reactComponentSpec;
  exports["reactPropFields"] = reactPropFields;
  exports["statelessComponent"] = $foreign.statelessComponent;
  exports["getProps"] = $foreign.getProps;
  exports["getState"] = $foreign.getState;
})(PS["React"] = PS["React"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Monad_Reader = PS["Control.Monad.Reader"];
  var Control_Monad_Reader_Trans = PS["Control.Monad.Reader.Trans"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Nullable = PS["Data.Nullable"];
  var Data_Unit = PS["Data.Unit"];
  var Effect = PS["Effect"];
  var Effect_Class = PS["Effect.Class"];
  var Effect_Ref = PS["Effect.Ref"];
  var Effect_Uncurried = PS["Effect.Uncurried"];
  var Prelude = PS["Prelude"];
  var React = PS["React"];
  var renderer = function (f) {
      return function ($$this) {
          return function __do() {
              var v = React.getProps($$this)();
              var v1 = React.getState($$this)();
              return f({
                  state: v1,
                  props: v
              });
          };
      };
  };
  var reactReaderT = Control_Monad_Reader_Trans.ReaderT;
  var getState = function (dictMonadEffect) {
      return reactReaderT(function ($10) {
          return Effect_Class.liftEffect(dictMonadEffect)(React.getState($10));
      });
  };
  var getProps = function (dictMonadEffect) {
      return reactReaderT(function ($11) {
          return Effect_Class.liftEffect(dictMonadEffect)(React.getProps($11));
      });
  };
  exports["getProps"] = getProps;
  exports["getState"] = getState;
  exports["renderer"] = renderer;
})(PS["Dispatcher.React"] = PS["Dispatcher.React"] || {});
(function(exports) {const RN = require("react-native")

  exports.registerComponent = function(name){
    return function(component){
      return function(){
        RN.AppRegistry.registerComponent(name, function(){ return component; });
      }
    }
  }
})(PS["ReactNative.API"] = PS["ReactNative.API"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["ReactNative.API"];
  var Data_Function_Uncurried = PS["Data.Function.Uncurried"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Nullable = PS["Data.Nullable"];
  var Data_Unit = PS["Data.Unit"];
  var Effect = PS["Effect"];
  var React = PS["React"];
  exports["registerComponent"] = $foreign.registerComponent;
})(PS["ReactNative.API"] = PS["ReactNative.API"] || {});
(function(exports) {
    'use strict';

  const RN = require("react-native");                          
  exports.buttonClass                   = RN.Button;        
  exports.textClass                     = RN.Text;                    
  exports.viewClass                     = RN.View;
})(PS["ReactNative.Unsafe.Components"] = PS["ReactNative.Unsafe.Components"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["ReactNative.Unsafe.Components"];
  var React = PS["React"];                                            
  var viewU = React.unsafeCreateElement($foreign.viewClass);                    
  var textU = React.unsafeCreateElement($foreign.textClass);                      
  var buttonU = React.unsafeCreateLeafElement($foreign.buttonClass);
  exports["textU"] = textU;
  exports["viewU"] = viewU;
  exports["buttonU"] = buttonU;
})(PS["ReactNative.Unsafe.Components"] = PS["ReactNative.Unsafe.Components"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Prelude = PS["Prelude"];
  var React = PS["React"];
  var ReactNative_Events = PS["ReactNative.Events"];
  var ReactNative_Optional = PS["ReactNative.Optional"];
  var ReactNative_PropTypes_Color = PS["ReactNative.PropTypes.Color"];
  var ReactNative_Unsafe_ApplyProps = PS["ReactNative.Unsafe.ApplyProps"];
  var ReactNative_Unsafe_Components = PS["ReactNative.Unsafe.Components"];                 
  var button_ = function (title) {
      return ReactNative_Unsafe_Components.buttonU({
          title: title
      });
  };
  exports["button_"] = button_;
})(PS["ReactNative.Components.Button"] = PS["ReactNative.Components.Button"] || {});
(function(exports) {
    'use strict';

  const RN = require('react-native');

  function styles(sarr) {
    var result = {};

    for (var i = 0, len = sarr.length; i < len; i++) {
      var style = sarr[i];

      for (var key in style) {
        if (style.hasOwnProperty(key)) {
          result[key] = style[key];
        }
      }
    }
    return result;
  }

  exports.styles = styles

  exports.staticStyles = function(sarr) {
    return RN.StyleSheet.create({s:styles(sarr)}).s;
  };

  exports.unsafeStyleProp = function(s) {
    return function(v) {
      var o = {};
      o[s] = v;
      return o;
    }
  }
})(PS["ReactNative.Styles"] = PS["ReactNative.Styles"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["ReactNative.Styles"];
  var ReactNative_PropTypes = PS["ReactNative.PropTypes"];
  var ReactNative_PropTypes_Color = PS["ReactNative.PropTypes.Color"];
  var Unsafe_Coerce = PS["Unsafe.Coerce"];                        
  var marginTop = $foreign.unsafeStyleProp("marginTop");
  exports["marginTop"] = marginTop;
  exports["staticStyles"] = $foreign.staticStyles;
})(PS["ReactNative.Styles"] = PS["ReactNative.Styles"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var React = PS["React"];
  var ReactNative_Components = PS["ReactNative.Components"];
  var ReactNative_Events = PS["ReactNative.Events"];
  var ReactNative_Optional = PS["ReactNative.Optional"];
  var ReactNative_Styles = PS["ReactNative.Styles"];
  var ReactNative_Unsafe_ApplyProps = PS["ReactNative.Unsafe.ApplyProps"];
  var ReactNative_Unsafe_Components = PS["ReactNative.Unsafe.Components"];
  var Unsafe_Coerce = PS["Unsafe.Coerce"];
  var textElem = Unsafe_Coerce.unsafeCoerce;
  var text_ = function (s) {
      return ReactNative_Unsafe_Components.textU({})([ textElem(s) ]);
  };
  exports["textElem"] = textElem;
  exports["text_"] = text_;
})(PS["ReactNative.Components.Text"] = PS["ReactNative.Components.Text"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Prelude = PS["Prelude"];
  var React = PS["React"];
  var ReactNative_Components = PS["ReactNative.Components"];
  var ReactNative_Events = PS["ReactNative.Events"];
  var ReactNative_Optional = PS["ReactNative.Optional"];
  var ReactNative_PropTypes = PS["ReactNative.PropTypes"];
  var ReactNative_Styles = PS["ReactNative.Styles"];
  var ReactNative_Unsafe_ApplyProps = PS["ReactNative.Unsafe.ApplyProps"];
  var ReactNative_Unsafe_Components = PS["ReactNative.Unsafe.Components"];
  var Unsafe_Coerce = PS["Unsafe.Coerce"];
  var view_ = ReactNative_Unsafe_Components.viewU({});
  var view = function (style) {
      return ReactNative_Unsafe_Components.viewU({
          style: style
      });
  };
  exports["view_"] = view_;
  exports["view"] = view;
})(PS["ReactNative.Components.View"] = PS["ReactNative.Components.View"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Applicative = PS["Control.Applicative"];
  var Dispatcher_React = PS["Dispatcher.React"];
  var Effect = PS["Effect"];
  var Prelude = PS["Prelude"];
  var React = PS["React"];
  var ReactNative_API = PS["ReactNative.API"];
  var ReactNative_Components_Button = PS["ReactNative.Components.Button"];
  var ReactNative_Components_Text = PS["ReactNative.Components.Text"];
  var ReactNative_Components_View = PS["ReactNative.Components.View"];
  var ReactNative_Styles = PS["ReactNative.Styles"];                 
  var sheet = {
      container: ReactNative_Styles.staticStyles([ ReactNative_Styles.marginTop(64) ])
  };
  var initialState = {
      nextId: 0,
      items: [  ]
  };
  var itemsListClass = (function () {
      var spec = function ($$this) {
          var render = function (v) {
              return ReactNative_Components_View.view_([ ReactNative_Components_Button.button_("A Button"), ReactNative_Components_Text.text_("Hello again") ]);
          };
          return Control_Applicative.pure(Effect.applicativeEffect)({
              render: Dispatcher_React.renderer(render)($$this),
              state: initialState
          });
      };
      return React.component(React.reactComponentSpec()())("ItemsList")(spec);
  })();
  var itemsList = React.createLeafElement(React.reactPropFields()())(itemsListClass);
  var app = (function () {
      var render = function (v) {
          return ReactNative_Components_View.view(sheet.container)([ ReactNative_Components_Text.text_("This is a list!"), itemsList({}) ]);
      };
      return React.statelessComponent(render);
  })();
  var main = ReactNative_API.registerComponent("HealthTrack")(app);
  exports["itemsListClass"] = itemsListClass;
  exports["initialState"] = initialState;
  exports["itemsList"] = itemsList;
  exports["app"] = app;
  exports["sheet"] = sheet;
  exports["main"] = main;
})(PS["Main"] = PS["Main"] || {});
PS["Main"].main();
